### ISSUE TITLE
解析出现的一些问题

### ISSUE THREAD

**Issue by xu42** [hit9/thriftr#1]
使用该脚本时存在的问题：
.thrift 解析后的字符串不是标准的json格式，我测试解析后的字符串引号是单引号，但给的example却是双引号的标准格式。其它的还有 None应为 null，False应为false，True应为true。

mac OS ，python2.7

**Comment by hit9** [comment]
这个repo很久没有维护了 请移步 thriftpy github.com/eleme/thriftpy

**Comment by xu42** [comment]
@hit9 thriftpy没有parser部分的文档，是否可提供这方面的文档或demo ？，thriftr的readme里面的示例是不正确的。

**Comment by hit9** [comment]
这个repo不维护了.

thriftpy的parser使用只是提供了一个接口啊 `thriftpy.load`

**Comment by xu42** [comment]
谢谢你
